--WHAT IS THE TOTAL REVENUE GENERATED BY MALE VS FEMALE ?
SELECT * 
FROM customer_shopping_behavior

SELECT gender,SUM(purchased_amount) AS revenue
FROM customer_shopping_behavior
GROUP BY gender

--WHICH CUSTOMER USED A DISCOUNT BUT STILL SPENT MORE THAN THE AVERAGE PURCHASE AMOUNT ?
SELECT customer_id,purchased_amount
FROM customer_shopping_behavior
WHERE discount_applied = 'Yes'
	AND purchased_amount >= (SELECT AVG(purchased_amount) FROM customer_shopping_behavior)

--WHICH ARE THE TOP 5 PRODUCTS WITH THE HIGHEST AVERAGE REVIEW RATING
SELECT TOP 5 item_purchased,CAST(AVG(review_rating) AS DECIMAL(10,2)) AS average_product_rating
FROM customer_shopping_behavior
GROUP BY item_purchased
ORDER BY average_product_rating DESC

--COMPARE THE AVERAGE PURCHASE AMOUNTS BETWEEN STANDARD AND EXPRESS SHIPPING
SELECT shipping_type,CAST(AVG(purchased_amount) AS DECIMAL(10,2)) AS avg_purchase_amount
FROM customer_shopping_behavior
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type

--DO SUBSCRIBED CUSTOMERS SPEND MORE ? COMPARE AVERAGE SPEND AND TOTAL REVENUE BETWEEN SUBSCRIBERS AND NON-SUBSCRIBERS
SELECT subscription_status,
	COUNT(customer_id) AS total_customers,
	CAST(AVG(purchased_amount) AS DECIMAL(10,2)) AS avg_spend,
	sum(purchased_amount) AS total_revenue
FROM customer_shopping_behavior
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC


--WHICH 5 PRODUCTS HAVE THE HIGHEST PERCENTAGE OF PURCHASES WITH DISCOUNT APPLIED ?
SELECT TOP (5) item_purchased,
	CAST(SUM(CASE WHEN discount_applied = 'YES' THEN 1
	ELSE 0 
	END )*100.0/COUNT(*) AS DECIMAL(10,2)) AS discount_percentage
FROM customer_shopping_behavior
GROUP BY item_purchased
ORDER BY discount_percentage DESC

--SEGMENT CUSTOMERS INTO NEW, RUNNING. AND LOYAL BASED ON THEIR TOTAL NUMBER OF PREVIOUS PURCHASES AND SHOW THE COUNT OF EACH SEGMENT 
WITH CUSTOMER_TYPE AS (
		SELECT customer_id,previous_purchases,
			CASE WHEN previous_purchases = 1 THEN 'NEW' 
			WHEN previous_purchases BETWEEN 2 AND 10 THEN 'RUNNING' 
			ELSE 'LOYAL'
			END AS CUSTOMER_SEGMENT
		FROM customer_shopping_behavior )
SELECT CUSTOMER_SEGMENT,COUNT(CUSTOMER_SEGMENT) AS number_of_customers
FROM CUSTOMER_TYPE
GROUP BY CUSTOMER_SEGMENT;

--WHAT ARE THE TOP 3 MOST PURCHASED PRODUCTS WITHIN EACH CATEGORY?
WITH item_count AS (
SELECT category,item_purchased,
COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER(PARTITION BY CATEGORY ORDER BY COUNT(CUSTOMER_ID) DESC ) AS item_rank
FROM customer_shopping_behavior
GROUP BY category,item_purchased)
SELECT item_rank,category,item_purchased,total_orders
FROM item_count
WHERE item_rank <= 3;

--ARE CUSTOMERS WHO ARE REPEAT BUYERS (MORE THAN 5 PREVIOUS PURCHASES) ALSO LIKE TO SUBSCRIBE
SELECT subscription_status,COUNT(customer_id) AS REPEAT_BUYERS
FROM customer_shopping_behavior
WHERE previous_purchases > 5
GROUP BY subscription_status

--WHAT IS THE REVENUE CONTRIBUTION OF EACH AGE GROUP ?
SELECT age_group,SUM(purchased_amount) AS TOTAL_REVENUE
FROM customer_shopping_behavior
GROUP BY age_group
ORDER BY TOTAL_REVENUE








--